src/custom_user/urls.py
from django.conf.urls import url
from .views import home,login, loggedin, logout, invalid_login, register_user, register_success

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^loggedin/$', loggedin, name='loggedin'),
    url(r'^invalid/$', invalid_login, name='invalid'),
    url(r'^register/$', register_user, name='register'),
    url(r'^register_success/$', register_success, name='register_success'),
]

src/customauth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("custom_user.urls", namespace='accounts')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/custom_user/models.py
import datetime

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _

now = datetime.datetime.now()


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = datetime.datetime.now()

        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=254, unique=True, blank=True, null=True)
    first_name = models.CharField(max_length=254, blank=True)
    last_name = models.CharField(max_length=254, blank=True)
    email = models.EmailField(unique=True)
    address1 = models.CharField(max_length=254, blank=True)
    address2 = models.CharField(max_length=254, blank=True)
    area_code = models.CharField(max_length=20, blank=True)
    country_code = models.CharField(max_length=10, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    # is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'address1', 'address2', 'area_code', 'country_code']

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])

src/custom_user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)

    class Meta:
        model = CustomUser
        fields = ["username", "email"]


class CustomUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserChangeForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = CustomUser
        fields = '__all__'


class LoginForm(forms.Form):
    user_exist = False
    email = forms.EmailField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            CustomUser.objects.get(email=email)
            self.user_exist = True
        except CustomUser.DoesNotExist:
            raise forms.ValidationError("Are you sure you are registered? We cannot find this user.")
        return email

    def clean_password(self):
        if self.user_exist:
            email = self.cleaned_data.get("email")
            user = CustomUser.objects.get(email=email)
            password = self.cleaned_data.get("password")
            if user.check_password(password):
                return password
            else:
                raise forms.ValidationError("Invalid Password")

src/custom_user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
from .forms import LoginForm
from .models import CustomUser
from django.contrib import messages
from custom_user.forms import CustomUserCreationForm


def home(request):
	if request.user.is_authenticated() and request.user.is_staff:
		queryset = CustomUser.objects.all().order_by('-date_joined')
		context = {
			"queryset": queryset
		}
	else:
		context = {"queryset": "welcome"}
	return render(request, "home.html", context)


def login(request):
	form = LoginForm(request.POST or None)
	btn = "Login"
	if form.is_valid():
		email = form.cleaned_data['email']
		password = form.cleaned_data['password']
		user = auth.authenticate(username=email, password=password)
		if not user: return HttpResponseRedirect(reverse('accounts:invalid'))
		auth.login(request, user)
		messages.success(request, "Successfully Logged In. Welcome Back!")
		return HttpResponseRedirect(reverse('accounts:loggedin'))
	context = {
		"form": form,
		"submit_btn": btn,
	}
	return render(request, "login.html", context)

def loggedin(request):
	return render(request, 'loggedin.html',
				  {'user': request.user})


def invalid_login(request):
	return render(request, 'invalid_login.html')


def logout(request):
	auth.logout(request)
	return render(request, 'logout.html')


def register_user(request):
	form = CustomUserCreationForm(request.POST or None)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('accounts:register_success'))
	args = {}
	args.update(csrf(request))

	args['form'] = form

	return render(request, 'register.html', args)


def register_success(request):
	return render(request, 'register_success.html')

src/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Email Auth Tutorial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <style type="text/css">
      body { padding-top: 60px; }
    </style>
    
  </head>
  <body>
  
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Email Auth App</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->
    
    <div class="container">
    {% if user.is_authenticated %}
        You are currently logged in as {{ user.email }}, not you? <a href="{% url 'accounts:logout' %}">Sign out</a>
    {% else %}
        <a href="{% url 'accounts:register' %}">Register</a> or <a href="{% url 'accounts:login' %}">Login</a>
    {% endif %}
    {% block content %}
    
    {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}


{% block head_title %}Welcome | {{ block.super }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
}

.jumbotron {
	background-color:#0E3D14;
	color: #FFF;
}

{% endblock %}
</style>



{% block content %}
     {% if not request.user.is_authenticated %}

        <div class="jumbotron">
         <div class="container">
            <div class="row">
                <div class='col-sm-6'>
                <h1>custom auth</h1>
                <p> You should logged as staff in order to edit or delete users....</p>
                </div>
                </div>
            </div>
         </div>
     {% else %}

        <h1>You are logged in!</h1>

            {% if queryset %}
            <h2>Welcome Staff</h2>
            <table class='table'>
            {% for instance in queryset %}
                <tr><td>{{ forloop.counter }}</td>
                <td>{{ instance.email }}</td>
                <td>{{ instance.date_joined }} ago</td>
                <td><a href="{{instance.id}}/edit/">Edit</a></td>
                <td><a href="{{instance.id}}/del/">Del</a></td>
                </tr>
            {% endfor %}
            </table>
            {% endif %}
    {% endif %}


{% endblock content%}

src/templates/invalid_login.html
{% extends "base.html" %}

{% block content %}

  <h2>Your login details are invalid!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again.</p>

{% endblock %}

src/templates/loggedin.html
{% extends "base.html" %}

{% block content %}

  <h2>Hi {{user.email}} you are now logged in!</h2>
  
  <p>Click <a href="/accounts/logout/">here</a> to logout.</p>

{% endblock %}

src/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class='col-sm-6 col-sm-offset-3' style='margin-top: 50px;'>
    <form method='POST' action=''>{% csrf_token %}
        {{form.as_p}}
        <input type='submit' value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}'
               class='btn btn-default'/>
    </form>
</div>

{% endblock %}

src/templates/logout.html
{% extends "base.html" %}

{% block content %}

  <h2>Logged out!</h2>
  <p>Click <a href="{% url 'accounts:login' %}">here</a> to login again</p>

{% endblock %}

src/templates/register.html
{% extends "base.html" %}

{% block content %}
  
  <h2>Register</h2>
  
  {% for field in form %}
    {{field.error}}

  {% endfor %}
  <form action="{% url 'accounts:register'%}" method="post">
  {% csrf_token %}
  {{form.as_p}}

  
  <input type="submit" value="Register" />
    
  </form>
  
{% endblock %}

src/templates/register_success.html
{% extends "base.html" %}

{% block content %}

  <h2>You have registered!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again</p>

{% endblock %}